BCProjekt/Controllers/MeteoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BC.Context;
using BC.Helpers;
using BC.Models;
using System.Security.Claims;
using System.Threading;
using Microsoft.AspNetCore.Authorization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace BC.Controllers
{
    [Authorize]
    public class MeteoController : Controller
    {
        private readonly ContextDB _context;
        
        public MeteoController(ContextDB meteo)
        {
            _context = meteo;
        }
        public IActionResult Index()
        {

            return View();
        }
        public IActionResult Create(int? id)
        {
            if (id == null) { 
                var identity = (ClaimsIdentity)HttpContext.User.Identity;
                string currentUserID = identity.Claims.FirstOrDefault(u => u.Type == "usrID").Value;
                List<Device> devices = _context.Device.Where(u => u.User.UserID == int.Parse(currentUserID)).ToList();
                ViewData["Stations"] = devices;
                return View();
            }
            else {
                var device = _context.Device.Where(e => e.DevID == id).ToList();
                Device dev = new();
                foreach (var item in device)
                {
                    dev.Address = item.Address;
                    dev.Protocol = item.Protocol;
                    dev.PrefferedCommunication = item.PrefferedCommunication;
                    dev.LoadType = item.LoadType;
                    dev.Geolocation = item.Geolocation;
                    dev.TimeDelay = item.TimeDelay;
                    dev.Units = item.Units;
                    dev.Manufacturer = item.Manufacturer;
                }
                
                return View(dev);
            }
        }
        [HttpPost]
        public IActionResult Create(Device device, string options, string loadType, string protocol, IFormCollection values)
        {
            bool exists = true;

            var identity = (ClaimsIdentity)HttpContext.User.Identity;
            string currentUserID = identity.Claims.FirstOrDefault(u => u.Type == "usrID").Value;
            User user = _context.User.FirstOrDefault(u => (u.UserID == int.Parse(currentUserID)));

            var existingDevices = _context.Device.Where(e=>e.User.UserID == user.UserID);
            var onlyDevicesNames = existingDevices.Select(u => u.Name).ToList();

            if (!onlyDevicesNames.Contains(device.Name))
                exists = false;
            
            if(!exists){
                if (!ModelState.IsValid)
                {
                    return View(device);
                    
                }
                singleData.returnInstance().Communicaton = values["options"];
                singleData.returnInstance().DataType = values["LoadType"];
                singleData.returnInstance().Protocol = values["protocol"];
                var units = values["Units"];
                var senTmp = values["sensorsSelect"];
                List<Sensors> sensorItem = new();
                
                for (int i = 0; i < senTmp.Count; i++)
                {
                    Sensors sensor = new();
                    sensor.Name = senTmp[i];
                    sensorItem.Add(sensor);
                }
                

                if (!string.IsNullOrEmpty(values["URLFormat"])) { 
                    singleData.returnInstance().URLFormat = values["URLFormat"];
                    device.UrlFormat = values["URLFormat"];
                }

                device.User = user;
                device.LoadType = loadType;
                device.Protocol = protocol;
                device.Sensors = sensorItem;
                device.Units = units;
                device.PrefferedCommunication = options;
                _context.Device.Add(device);
                
                _context.SaveChanges();
                
                
                return RedirectToAction("Index", "Home");
            }
            ViewData["CreateModelError"] = "Device with that name already exists!";
            return View();
        }
        public IActionResult ListStations()
        {
            var tmp = (ClaimsIdentity)HttpContext.User.Identity;
            string currentUserID = tmp.Claims.FirstOrDefault(u => u.Type == "usrID").Value;
            List<Device> devices = _context.Device.Where(u=>u.User.UserID == int.Parse(currentUserID)).ToList();
            
            return View(devices.AsEnumerable());
        }
        public async Task <IActionResult> Edit(int? id)
        {
            var device = await _context.Device.FindAsync(id);

            var getSensors = _context.Device.Include(tmp => tmp.Sensors).FirstOrDefault(u => u.DevID == id);
            var selectedSensors = getSensors.Sensors;
            device.Sensors = selectedSensors;
            return View(device);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Device device, int id, IFormCollection values)
        {
            if (id != device.DevID)
                return NotFound();
            //Device dev = _context.Device.FirstOrDefault(u=> u.DevID == values["DevID"]);
            if (ModelState.IsValid)
            {
                var sensors = values["ItemName"];
                var senTmp = values["editSensorsSel"];
                List<Sensors> sensorItem = new();

                for (int i = 0; i < sensors.Count; i++)
                {
                    Sensors sensor = new();
                    sensor.Name = sensors[i];
                    sensorItem.Add(sensor);
                }
                for (int i = 0; i < senTmp.Count; i++)
                {
                    Sensors sensor = new();
                    sensor.Name = senTmp[i];
                    sensorItem.Add(sensor);
                }
                var oldItems = _context.Sensors.Where(sen => sen.Device.DevID == device.DevID);
                _context.Sensors.RemoveRange(oldItems);
                device.Sensors = sensorItem;
                device.PrefferedCommunication = values["options"];
                _context.Update(device);
                await _context.SaveChangesAsync();
                return RedirectToAction("ListStations");
            }
            return View(device);
        }
        public IActionResult Details(int? id)
        {
            Device device = _context.Device.Find(id);
            //
            return View(device);
        }


        public IActionResult Delete(int? id)
        {
            Device devices = _context.Device.Find(id);
            return View(devices);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var devices = await _context.Device.FindAsync(id);
            var dev = _context.Device.Where(e => e.DevID == id).Include(e => e.Sensors).First();

            _context.Remove(dev);
            await _context.SaveChangesAsync();
            return RedirectToAction("ListStations");
        }


        public IActionResult AdvancedDetails(int ? id)
        {
            Device device = _context.Device.Find(id);
            var getSensors = _context.Device.Include(tmp => tmp.Sensors).FirstOrDefault(u=>u.DevID==id);
            var selectedSensors = getSensors.Sensors;
            device.Sensors = selectedSensors;

            return View(device);
        }
    }
}

BCProjekt/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Helpers;
using BC.Context;
using BC.Models;
using Microsoft.AspNetCore.Authorization;
using System;
using Microsoft.EntityFrameworkCore;

namespace BC.Controllers
{
    public class UserController : Controller
    {
        private readonly ContextDB _context;
        public UserController(ContextDB user)
        {
            _context = user;
        }
        public IActionResult Index()
        {
            var tmp = (ClaimsIdentity)HttpContext.User.Identity;
            string currentUserID = tmp.Claims.FirstOrDefault(u => u.Type == "usrID").Value;
            List<User> users = _context.User.Where(u=>u.UserID == int.Parse(currentUserID)).ToList();

            return View(users.AsEnumerable());
        }
        public async Task<IActionResult> Edit(int? id)
        {
            var user = await _context.User.FindAsync(id);
            return View(user);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(User user, int id, IFormCollection values)
        {
            if(id != user.UserID)
            {
                return NotFound();
            }
            
            if (ModelState.IsValid)
            {
                try
                {
                    user.Password = Crypto.HashPassword(user.Password);
                    _context.Update(user);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException e)
                {

                    throw e.InnerException;
                }
               
            }
            return View(user);
        }

        [AllowAnonymous]
        public IActionResult Register()
        {
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(IFormCollection data, User user)
        {
            if (ModelState.IsValid)
            {
                if (_context.User.FirstOrDefault(u => u.Login == data["Login"].ToString()) == null)
                {
                    user.Registered = DateTime.Now;
                    user.LastLogin = DateTime.Now;
                    //Hashing users password
                    user.Password = Crypto.HashPassword(user.Password);
                    _context.User.Add(user);
                

                    await _context.SaveChangesAsync();
                    TempData["Success"] = "User sucessfully added!";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ViewData["Failure"] = "User already exists!";
                return View();
            }
            ViewData["Failure"] = "Please fix the input!";
            return View();
        }
    }
}

BCProjekt/Controllers/WeatherApiController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using BC.Context;
using BC.Models;

namespace BC.Controllers
{
    public class WeatherApiController : Controller
    {
        private readonly ContextDB _context;
        public WeatherApiController(ContextDB meteo)
        {
            _context = meteo;
        }
        public IActionResult Index()
        {
            var tmp = (ClaimsIdentity)HttpContext.User.Identity;
            string currentUserID = tmp.Claims.FirstOrDefault(u => u.Type == "usrID").Value;

            List<Device> device = _context.Device.Where(u => u.User.UserID == int.Parse(currentUserID)).ToList();
            return View(device.AsEnumerable()) ;
        }
    }
}

BCProjekt/Views/Home/ErrorLogin.cshtml
@{
	ViewBag["Title"] = "Error page";
}
<h2>Something went wrong, maybe this function wasnt implemented yet! For more information contact administrator.</h2>

<a asp-action="Index">Back to List</a>

BCProjekt/Views/Home/GetStation.cshtml
@using BC;
@model dynamic
@{
    ViewData["Title"] = "Home Page";
}
@{
    var identity = (System.Security.Claims.ClaimsIdentity)Context.User.Identity;
    var name = identity.Claims.FirstOrDefault(c => c.Type == "user").Value;
}
<div class="container">
    <div class="background-circle">
        <div class="row h-100">
                        <div class="col-sm-1">
                                <a class="btn-my" asp-action="Index" asp-controller="Home">
                                            <span class="button__icon">
                                                    <ion-icon name="home-outline"></ion-icon>
                                            </span>
                                 </a>
                                <a class="btn-my" asp-action="Index" asp-controller="User">
                                        <span class="button__icon"  >
                                                <ion-icon name="person-outline"></ion-icon>
                                        </span>
                                </a>
                                <a  class="btn-my" asp-action="Create" asp-controller="Meteo" asp-area="">
                                        <span class="button__icon">
                                                <ion-icon name="add-outline"></ion-icon>
                                        </span>
                                </a>
                                <a  class="btn-my" asp-action="ListStations" asp-controller="Meteo" asp-area="">
                                        <span class="button__icon">
                                                <ion-icon name="hardware-chip-outline"></ion-icon>
                                        </span>
                                </a>
                                <a class="btn-my" asp-action="Graphs" asp-controller="GraphExport">
                                        <span class="button__icon">
                                                <ion-icon name="stats-chart-outline"></ion-icon>
                                        </span>
                                </a>
                                <a  class="btn-my" asp-action="Index" asp-controller="WeatherApi">
                                        <span class="button__icon">
                                                <i class="bi bi-cloud-moon"></i>
                                        </span>
                                        
                                </a>
                                <a class="btn-my" asp-action="Logout" asp-controller="Home">
                                        <span class="button__icon">
                                               <ion-icon name="log-out-outline"></ion-icon>
                                        </span>
                                        
                                </a>
                        </div>
                <div class="col-sm-11">
                            <div class="row g-2" >
                                <div class="col-sm-9 greetings">
                                    <div class="row row-align">
                                        <div class="col">
                                            <div class="greetings-text" id="greetings-text"></div>
                                            <div class="date" id="date">
                                            </div>
                                        </div>
                                        <div class="col-1"></div>
                                        <div class="col">
                                                
                                                <div class="time" id="time"></div>
                                        </div>
                                    </div>
                                </div>
                                    <div class="col-sm-3 meteo">
                                        <div class="dropdown-side">
                                            <button class="dropbtn-side">Choose meteostation</button>
                                            <div class="dropdown-content-side">
                                            @if(Model.Device.Count != 0){
                                                    @foreach(Device Device in Model.Device){
                                                        <a class="next" asp-area="" asp-controller="Home" asp-action="GetStation" asp-route-id="@Device.DevID">@Html.DisplayFor(modelItem => Device.Name)</a>
                                                        <br/>
                                                }
                                            }
                                            else{
                                                    <li class="navlink text-dark">No meteostations!</li>
                                            }
                                            </div>
                                        </div>
                                    </div>
            
                                    <div class="col-sm-9  bottom-div">
                                         <div id="content-wrapper" class="content-wrapper"></div>
                                            
                                    </div>

                                    <div class="col-sm-3" id="rightSideExtraData">
                                        <div class="row right-side">
                                            <div class="col-6">
                                                <div class="icons" id="icons">
                                            </div>
                                            </div>
                                            <div class="col-6">
                                                <div class="icons-text1" id="icons-text1"></div>
                                                <div class="icons-text" id="icons-text"></div>
                                            </div>
                                            
                                            
                                         </div>
                                    </div>
                            </div>
                    </div>
                </div>
    </div>
</div>
<script type="text/javascript">
    fillText();
    fillIcons();
    greetings('@name');
    setDate();
    setTime();
    
    getPostData('@Model.Manufacturer');

    var dt = new Date();
    window.setInterval(function () {
            getPostData();
        
    }, 10000);
    window.setInterval(function () {
            setTime();
        
    }, 1000*(60-dt.getSeconds()));

    window.setInterval(function () {
            setDate();
        
    }, 1000*(24-dt.getHours()));

</script>

BCProjekt/Views/Home/Index.cshtml
@using BC;
@model dynamic
@{
    ViewData["Title"] = "Home Page";
}
@{
    var identity = (System.Security.Claims.ClaimsIdentity)Context.User.Identity;
    var name = identity.Claims.FirstOrDefault(c => c.Type == "user").Value;
}
<div class="container">
    <div class="background-circle">
        <div class="row h-100">
                        <div class="col-sm-1">
                                <a class="btn-my" asp-action="Index" asp-controller="Home">
                                            <span class="button__icon">
                                                    <ion-icon name="home-outline"></ion-icon>
                                            </span>
                                 </a>
                                <a class="btn-my" asp-action="Index" asp-controller="User">
                                        <span class="button__icon"  >
                                                <ion-icon name="person-outline"></ion-icon>
                                        </span>
                                </a>
                                <a  class="btn-my" asp-action="Create" asp-controller="Meteo" asp-area="">
                                        <span class="button__icon">
                                                <ion-icon name="add-outline"></ion-icon>
                                        </span>
                                </a>
                                <a  class="btn-my" asp-action="ListStations" asp-controller="Meteo" asp-area="">
                                        <span class="button__icon">
                                                <ion-icon name="hardware-chip-outline"></ion-icon>
                                        </span>
                                </a>
                                <a class="btn-my" asp-action="Graphs" asp-controller="GraphExport">
                                        <span class="button__icon">
                                                <ion-icon name="stats-chart-outline"></ion-icon>
                                        </span>
                                </a>
                                <a  class="btn-my" asp-action="Index" asp-controller="WeatherApi">
                                        <span class="button__icon">
                                                <i class="bi bi-cloud-moon"></i>
                                        </span>
                                        
                                </a>
                                <a class="btn-my" asp-action="Logout" asp-controller="Home">
                                        <span class="button__icon">
                                               <ion-icon name="log-out-outline"></ion-icon>
                                        </span>
                                        
                                </a>
                                
                        </div>
                <div class="col-sm-11">
                            <div class="row" >
                                <div class="col-sm-9 greetings">
                                    <div class="row row-align">
                                        <div class="col">
                                            <div class="greetings-text" id="greetings-text"></div>
                                            <div class="date" id="date"> </div>
                                            
                                        </div>
                                        <div class="col-1"></div>
                                        <div class="time" id="time"></div>
                                    </div>
                                </div>
                                    <div class="col-sm-3 meteo">
                                        <div class="dropdown-side">
                                            <button class="dropbtn-side">Choose meteostation</button>
                                            <div class="dropdown-content-side">
                                            @if(Model.Device.Count != 0){
                                                    @foreach(Device device in Model.Device){
                                                        <a class="next" asp-area="" asp-controller="Home" asp-action="GetStation" asp-route-id="@device.DevID">@Html.DisplayFor(modelItem => device.Name)</a>
                                                        <br/>
                                                }
                                            }
                                            else{
                                                    <li class="navlink text-dark">No meteostations!</li>
                                            }
                                            </div>
                                        </div>
                                    </div>
            
                                    <div class="col-sm-9 bottom-div">

                                         <div id="content-wrapper" class="content-wrapper"></div>
                                            
                                    </div>

                                    <div class="col-sm-3">
                                        <div class="row right-side" style="display:none;">
                                            <div class="col-6">
                                                <div class="icons" id="icons">
                                            </div>
                                            </div>
                                            <div class="col-6">
                                                <div class="icons-text1" id="icons-text1"></div>
                                                <div class="icons-text" id="icons-text"></div>
                                            </div>
                                            
                                            
                                         </div>
                                    </div>
                            </div>
                    </div>
                </div>
    </div>
</div>
<script type="text/javascript">
    fillText();
    fillIcons();
    greetings('@name');
    setDate();
    setTime();
    getPostData();
    var dt = new Date();
    window.setInterval(function () {
            getPostData();
        
    }, 60000);
    window.setInterval(function () {
            setTime();
        
    }, 1000*(60-dt.getSeconds()));

    window.setInterval(function () {
            setDate();
        
    }, 1000*(24-dt.getHours()));

</script>

BCProjekt/Views/Home/Login.cshtml
@model BC.Models.User
<div class="loginPageDiv shadow-lg p-3 mb-5 rounded">
        <h2>Please log in</h2>
        <form asp-controller="Home" asp-action="Login" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" role="form">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @if (@ViewBag.Message != null)
            {
                <div class="alert alert-danger d-flex align-items-center" role="alert">
                    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                    <div>
                        @ViewBag.Message
                    </div>
                </div>
            }

            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" type="text" class="form-control"/>
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control"/>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>


            <div class="row justify-content-center">
                <div class="col-3">
                    <button type="submit" value="Log in" class="btn btn-primary login-btn" style="width:100%;">Log in</button>
                </div>
            </div>

        </form>
        <div class="row justify-content-center">
                <div class="col-3">
                    <a class="btn btn-primary login-btn" asp-action="Register" asp-controller="Home" style="width:100%;">Register</a>
                </div>
        </div>
</div>